spring.application.name=BackPeluqueria
server.port=3000
#server.servlet.context-path=/lineafina

# =========================
# = DATA SOURCE
# =========================

#Indicamos el driver o libreria para conectar java con la base de datos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#url donde esta el servidor de BD y el nombre del esquema
spring.datasource.url=jdbc:mysql://localhost:3307/peluqueria_saas

#usuario y password de conexion al esquema
spring.datasource.username=rootpeluqueria
spring.datasource.password=LineaFina%23


# =========================
# = JPA / HIBERNATE
# =========================

#Permite a Hibernate generar SQL optimizado para un sistema gestor de BD en particular, acelerando de esta forma el acceso a la BD
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#Permite a Hibernate generar o actualizar de forma autom�tica el esquema de BD de acuerdo a las entidades java encontradas en el proyecto. Valores son: CREATE, CREATE-DROP, UPDATE , NONE
spring.jpa.hibernate.ddl-auto=none
#Parametro opcional que imprime en la consola las instrucciones SQL hechas para el esquema de la BD, pero no muestra los par�metros. Parecido al LOG
spring.jpa.show-sql=true

# ==========================
# = LOGGING. Sentencias SQL y parametros
#===========================
#Registra todas las declaraciones DML de SQL a medida que se ejecutan. 
#logging.level.org.hibernate.SQL=DEBUG
#Registra todos los par�metros JDBC.
logging.level.org.hibernate.type=TRACE


# carpeta relativa donde se guardaran los archivos (puede ser absoluta): se usa junto a @ConfigurationProperties(prefix="app.upload") ; @Component (se usa para que Spring gestione la clase pero no encaja como @Service, @Controller...)
#app.upload.dir=uploads
carpeta.fotos.subidas=uploads
# opcional: tamanyo maximo permitido en Spring (evita uploads enormes)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#clave que firma los tokens
jwt.secret=miclavesupersecretaparajwt2026lineafina



#Propiedad que indica a SpringBoot que perfil usar
#spring.profiles.active=dev 
#spring.profile.active=prod
#PlanetScale Base de Datos conectada a Azure
#Servidor de Correo, SendGrid, tiene integracion perfecta con Azure, configurar un subdominio para cada empresa

