spring.datasource.url=jdbc:mysql://localhost:3306/peluquerialineafina

#usuario y password de conexion al esquema en desarrollo
spring.datasource.username=rootpeluqueria
spring.datasource.password=LineaFina%23