spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

jwt.secret=${JWT_SECRET}

spring.application.name=PRODUCCION-RAILWAY
logging.level.root=DEBUG